# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
python:
    - 3.8
    - 3.7

# what branches should be evaluated
branches:
    only:
        - main
        - dev

# list of commands to run to setup the environment
install:
    - pip install coverage
    - pip install coveralls
    - pip install flake8
    - pip install -r requirements.txt

# go into seattlepark folder
# a list of commands to run before the main script
before_script:
    - pwd
    - ls -al
    - export PYTHONPATH=$PYTHONPATH:"$PWD/seattlepark/tests":"$PWD/seattlepark/src"
#    - flake8 -v seattlepark


# the actual commands to run
script:
   - coverage run -m unittest discover

# generate a coverage report to send to back to user
# exclude seattlepark/src/sea_street_parking_line because it is html
after_success:
   - coverage report --omit=seattlepark/src/parking_app.py
   - coveralls